"""First Migration

Revision ID: 931a418510c7
Revises: 
Create Date: 2023-05-22 13:52:25.189909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931a418510c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_id'), 'manga', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manga_id'), table_name='manga')
    op.drop_table('manga')
    # ### end Alembic commands ###
