"""Second Migration

Revision ID: b58ee24cd033
Revises: 931a418510c7
Create Date: 2023-05-22 14:22:55.009414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58ee24cd033'
down_revision = '931a418510c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
